---
title: "Пара вопросов от Байеса"
author: "Винни-Пух"
date: "6/18/2017"
output:
  word_document: default
  pdf_document: default
lang: ru-RU
---

## Вариант 1

### Вопрос 1
Выберите все верные утверждения про байесовский подход:

1. Неизвестные параметры трактуются как случайные величины

2. Для нахождения апостериорной распределения используется априорное распределение и функция правдоподобия

3. Байесовский подход позволяет получить только точечные, но не интервальные оценки параметров

4. В качестве точечной байесовской оценки неизвестного параметра можно использовать медиану апостериорного распределения.

5. В качестве точечной байесовской оценки неизвестного параметра можно использовать медиану априорного распределения.

6. Оценку максимального правдоподобия можно получить как максимум апостериорной плотности при постоянной априорной плотности.

Ответы: TTFTFT


### Вопрос 2

Василий оценивает неизвестный параметр $a>0$ с помощью байесовского подхода. Априорная функция плотности параметра $a$ пропорциональна $\exp(-2a)$. Функция правдоподобия пропорциональна $\exp(-a^2 + 2a)$. Апостериорная плотность при $a>0$ пропорциональна

1. $\exp(-a^2)$
2. $\exp(-a^2+2a) + \exp(-2a)$
3. $\exp(-a^2+2a) - \exp(-2a)$
4. $\exp(-2a) - \exp(-a^2+2a)$
5. $\exp(-a^2-4a)$


Ответ: TFFFF

## Вариант 2




### Вопрос 1
Выберите все верные утверждения про байесовский подход:

1. Неизвестные параметры трактуются как константы

2. Для нахождения апостериорной распределения используется априорное распределение и функция правдоподобия

3. Байесовский подход позволяет получить только интервальные, но не точечные оценки параметров

4. В качестве точечной байесовской оценки неизвестного параметра можно использовать среднее апостериорного распределения.

5. В качестве точечной байесовской оценки неизвестного параметра можно использовать среднее априорного распределения.

6. Оценку максимального правдоподобия можно получить как максимум априорной плотности при постоянной апостериорной плотности.

Ответы: FTFTFF

### Вопрос 2

Василий оценивает неизвестный параметр $a>0$ с помощью байесовского подхода. Априорная функция плотности параметра $a$ пропорциональна $\exp(-3a)$. Функция правдоподобия пропорциональна $\exp(-a^2 + 3a)$. Апостериорная плотность при $a>0$ пропорциональна

1. $\exp(-a^2)$
2. $\exp(-a^2+3a) + \exp(-3a)$
3. $\exp(-a^2+3a) - \exp(-3a)$
4. $\exp(-3a) - \exp(-a^2+3a)$
5. $\exp(-a^2-6a)$


Ответ: TFFFF
